[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
include = [
    {path = "octosuite/data/settings.json"}
]

name = "octosuite"
version = "3.2.0"
description = "An all-in-one GitHub open-source intelligence framework."
authors = ["Richard Mwewa <rly0nheart@duck.com>"]
readme = "README.md"
license = "GNU General Public License v3 (GPLv3)"
homepage = "https://www.bellingcat.com"
repository = "https://github.com/bellingcat/octosuite"
documentation = "https://github.com/bellingcat/octosuite/wiki"
keywords = ["github", "python", "github-api", "framework", "osint", "osint-framework", "osint-python", "osint-tool"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
  "Natural Language :: English"
]

[tool.poetry.dependencies]
python = "^3.9"
rich = { git = "https://github.com/rly0nheart/rich.git" }
psutil = "*"
requests = "*"
pyreadline3 = "*"

[tool.poetry.scripts]
octosuite = "octosuite.main:octosuite_non_cli"
octosuite-cli = "octosuite.main:octosuite_cli"
